### ISSUE TITLE
invalid json response 

### ISSUE THREAD

**Issue by Patabugen** [roelmagdaleno/cloudways-api-git-pull-action#1]
I've just set this up on a new repo and a new CloudWays app.

I'm getting this error:

`#invalid json response body at http://api.cloudways.com/ reason: Unexpected token < in JSON at position 0`

From a bit of a dig through your source I can't see where it might be coming from, but it seems to be on the access token fetch (since the logging events which come after that are not appearing in my logs.

That said... I can't see how/when it would ever call that URL without a path after it. But NodeJS is not my strong point!

Any suggestions for how I can troubleshoot or help you debug?

**Comment by roelmagdaleno** [comment]
@Patabugen I just re-run the last job in this [workflow](https://github.com/roelmagdaleno/roelmagdaleno.com-child-theme/runs/5605475054?check_suite_focus=true) and works perfectly.

So, some questions for you?

1. Did you setup [all secrets](https://github.com/roelmagdaleno/cloudways-api-git-pull-action#secrets)?
2. Did you follow all [configuration steps](https://github.com/roelmagdaleno/cloudways-api-git-pull-action#configuration)?
3. Can you send a screenshot of the issue in your GitHub Actions console? [Here's mine](https://user-images.githubusercontent.com/3928004/159069006-ce4001c2-3537-441e-bc14-86883aad61a0.png).
4. Also, I checked the Cloudways API Status, and there was a partial outage with Vultr servers today, maybe that affected you?
5. Did you re-run the workflow?

Let me know your answers, and thank you for using my GitHub Action.
Thanks.

**Comment by Patabugen** [comment]
Ah! I had missed the CLOUDWAYS_SERVER_ID secret!

Thanks you! And thanks for publishing the action, it was one of those wonderful moments when I initially couldn't find a CloudWays integration and started wondering if I'd have to make it - so it was great to find yours :)
