### ISSUE TITLE
Have a problem

### ISSUE THREAD

**Issue by AliaksandrShubkevich** [roelmagdaleno/cloudways-api-git-pull-action#4]
![image](https://github.com/roelmagdaleno/cloudways-api-git-pull-action/assets/120030925/b6f92f55-3c8d-4cfd-9ac5-1442f5ab02ee)

**Comment by roelmagdaleno** [comment]
Hello @AliaksandrShubkevich

Thanks for reporthing this, that's what I was afraid of. For some reason works sometimes.

If you're in a hurry to use the GitHub Action you can use the [v1.1.0](https://github.com/marketplace/actions/cloudways-api-git-pull?version=v1.1.0) version. In the meantime, I'll rollback that piece of code but I'll do it in ~2 hours.

Thanks.

**Comment by AliaksandrShubkevich** [comment]
Hello @roelmagdaleno 
I immediately reconfigured to the v1.1.0 version.
Thank you for your quick response and for your work, which makes our work easier. :)

**Comment by roelmagdaleno** [comment]
Hello @AliaksandrShubkevich

I deployed v1.2.1, so the `stable` branch is pointed to that tag now. That should fix the `require` issue. I also tested the GA with [nektos/act](https://github.com/nektos/act) and works correctly, let me know if it's working for you.

Thank you.

**Comment by AliaksandrShubkevich** [comment]
> 

Hello @roelmagdaleno 
I tested it, everything seems to be working well. Thanks for fixing it. Have a nice day.
