### ISSUE TITLE
Regularly fails when running in multiple jobs

### ISSUE THREAD

**Issue by Branch** [roelmagdaleno/cloudways-api-git-pull-action#6]
This seem to regularly fail when running in multiple jobs within an action. As a workaround we re-run the failed jobs until they succeed. This beats the purpose of setting up ci/cd since we always need to re-run failed jobs.

There's no error output:
Run roelmagdaleno/cloudways-api-git-pull-action@stable
  with:
    email: ***
    api-key: ***
    server-id: ***
    app-id: ***
    branch-name: ***

**Comment by roelmagdaleno** [comment]
Hello @Branch, can you paste here the entire output from the job that is failing? Thanks.
