### ISSUE TITLE
The jobs is failing. Could you please point me to the right direction? I am sharing full logs here.

### ISSUE THREAD

**Issue by sonevadeveloper** [roelmagdaleno/cloudways-api-git-pull-action#7]
##[debug]Evaluating condition for step: 'Cloudways API Git Pull'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Cloudways API Git Pull
##[debug]Loading inputs
##[debug]Evaluating: secrets.CLOUDWAYS_EMAIL
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'CLOUDWAYS_EMAIL'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: secrets.CLOUDWAYS_API_KEY
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'CLOUDWAYS_API_KEY'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: secrets.CLOUDWAYS_SERVER_ID
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'CLOUDWAYS_SERVER_ID'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: secrets.CLOUDWAYS_APP_ID
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'CLOUDWAYS_APP_ID'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: secrets.CLOUDWAYS_BRANCH_NAME
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'CLOUDWAYS_BRANCH_NAME'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: secrets.CLOUDWAYS_DEPLOY_PATH
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'CLOUDWAYS_DEPLOY_PATH'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run roelmagdaleno/cloudways-api-git-pull-action@stable
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Cloudways API Git Pull

**Comment by roelmagdaleno** [comment]
Hello @sonevadeveloper I don't see any error in that log, maybe the error is somewhere else or outside of this GH Action? Can you provide more logs? Thanks.

**Comment by sonevadeveloper** [comment]
Thanks for the reply. I've got a screenshot here. May be you can check it out? The job status here said it's failed. Is there anyway to check and get responses for the variables? I suspect that some of the variables are missing. I defined them all though.
![screencapture-github-sonevadeveloper-soneva-ms-actions-runs-7568873901-job-20715659912-2024-01-23-09_53_22](https://github.com/roelmagdaleno/cloudways-api-git-pull-action/assets/128341630/6914b25e-81af-48e8-b68e-991f4b84801c)

**Comment by roelmagdaleno** [comment]
@sonevadeveloper Thanks for the screenshot, it's the same as the output you shared in the beginning. Can you paste your workflow file? Thanks.

**Comment by sonevadeveloper** [comment]
@roelmagdaleno here is the workflow file.
name: Cloudways API Git Pull

on:
  push:
    branches:
      - "staging"

jobs:
  tag:
    name: staging-deploy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cloudways API Git Pull
        uses: roelmagdaleno/cloudways-api-git-pull-action@stable
        with:
          email: ${{ secrets.CLOUDWAYS_EMAIL }}
          api-key: ${{ secrets.CLOUDWAYS_API_KEY }}
          server-id: ${{ secrets.CLOUDWAYS_SERVER_ID }}
          app-id: ${{ secrets.CLOUDWAYS_APP_ID }}
          branch-name: ${{ secrets.CLOUDWAYS_BRANCH_NAME }}
          deploy-path: ${{ secrets.CLOUDWAYS_DEPLOY_PATH }}

**Comment by ee99ee** [comment]
Same issue here. This thing is totally broken. I think it's because it was built with Node 16 which is no longer supported by Github. Even if you force Node 20 by setting up a Node 20 step before running this action, it still just crashes. Bummer.

**Comment by roelmagdaleno** [comment]
@sonevadeveloper @ee99ee I released the `1.3.0` version. The action now uses `node20` and dependencies were updated as well. All new changes are in the `stable` branch.

Can you guys test?

I tested it on my end with a WordPress theme and [is working so far](https://github.com/roelmagdaleno/roelmagdaleno.com/actions/runs/8865458217/job/24341726412).

Let me know any feedback. Thank you.

**Comment by ee99ee** [comment]
Turns out the issue was related to unexpected input (`..` and `/`) of the `deploy-path` parameter.

@roelmagdaleno - I'll test 1.3.0
